# Base image
# for x32 systems.
FROM archlinux
# got x64 systems.
# FROM base/archlinux

# Maintainer :
MAINTAINER vincent montecot <vincent.montecot@hotmail.fr>

# Set ssh up.

# Copy private key into the container.

# Copy private key into the authorized_keys file

# Choose ports to expose

# Set Entrypoint to start sshd